name: Main workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4
      - name: Run shellcheck
        run: make lint

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4
      - name: Run shfmt
        run: make fmt-check

  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4
      - name: Run tests
        run: make test

  coverage:
    needs: [lint, style, test]
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
      - name: Install dependencies
        run: |
          bundle update --bundler
          bundle install
      - name: Run tests with coverage reporting
        run: make coverage
        continue-on-error: true
      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage/coverage.xml
        continue-on-error: true

  plugin-test:
    #needs: [coverage]
    needs: [lint, style, test]
    name: "Plugin test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        php-version:
          - latest:8.1
          - latest:8.2
          - latest:8.3
          - latest:8.4
    env:
      ASDF_PHP_VERBOSE: true
    steps:
      - name: Install and test version from plugin
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: php --version
          version: ${{ matrix.php-version }}
