name: Main workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        run: make lint

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install shfmt
        run: |
          curl -fsSL -o shfmt -C - https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/shfmt
      - name: Run shfmt
        run: make fmt-check

  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install bats-core (on Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          git clone https://github.com/bats-core/bats-core.git
          sudo ./bats-core/install.sh /usr/local
      - name: Install bats-core (on macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install bats-core
      - name: Check what bash version is installed
        run: |
          command -V bash
          bash --version
      - name: Run tests
        run: make test

  coverage:
    needs: [lint, style, test]
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.2"
      - name: Install dependencies
        run: |
          bundle update --bundler
          bundle install
          git clone https://github.com/bats-core/bats-core.git
          sudo ./bats-core/install.sh /usr/local
      - name: Run tests with coverage reporting
        run: make coverage
      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: coverage/coverage.xml

  plugin-test:
    needs: [coverage]
    name: "Plugin test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        php-version:
          - latest:8.0
          - latest:8.1
          - latest:8.2
          - latest:8.3
          - latest:8.4
    env:
      ASDF_PHP_VERBOSE: true
    steps:
      - name: Install and test version from plugin
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: php --version
          version: ${{ matrix.php-version }}
